@startuml

database "store 1" <<database>>
note bottom of "store 1" {
    type: mysql
    data-size: 100kb
}

component "service 1" <<service>>
note bottom of "service 1" {
    type: spring-boot
    request-delay: 100ms
    response-delay: 20ms
}

component "service 2" <<service>>
note bottom of "service 2" {
    type: spring-boot
    response-delay: 20ms
}

interface "port: 8080"

[service 1] -> [service 2]: HTTP/REST

[service 2] -> [store 1]: JDBC

[port: 8080] -> [service 1]: HTTP/REST

@enduml
