@startuml
!include <C4/C4_Container>

Container(service1, "service 1", "Spring Boot")
Container(service2, "service 2", "Go")
ContainerDb(store1, "store 1", "MySql")

Rel_R(service1, service2, "uses", "HTTP/REST")
Rel_R(service2, store1, "reads/writes", "JDBC")

note bottom of service1 {
    request-delay: 100ms
    response-delay: 20ms
}

note bottom of service2 {
    replicas: 5
}

note bottom of store1 {
    type: MySql
    datasize: 100kb
}
@enduml
