@startuml

database "myStore" <<database>>
note bottom of "myStore" {
    type: mysql
    data-size: 100kb
}

component "myService" <<service>>
note bottom of "myService" {
    type: spring-boot
    request-delay: 100ms
    response-delay: 20ms
}

interface "port: 8088"
interface "port: 5432"

[myService] -> [myStore]: JDBC
[port: 8088] -> [myService]: HTTP/REST
[port: 5432] --> [myStore]: JDBC

@enduml
