@startuml

database "myStore" <<database>>
note bottom of "myStore" {
    type: mongodb
}

component "myService" <<service>>
note bottom of "myService" {
    type: spring-boot
    request-delay: 5ms
    response-delay: 10ms
}

interface "port: 8080"
interface "port: 3306"

[myService] -> [myStore]: JDBC
[port: 8080] -> [myService]: HTTP/REST
[port: 3306] --> [myStore]: JDBC

@enduml
