@startuml
' comment

component Test <<service>>

note top of Test {
    variant: Quarkus
}

database "database 1"

note bottom of "database 1" {
    variant: PostgreSQL
    prop1: Test
    prop2: Foo
}

() JDBC - [database 1]
[Test] .> JDBC

@enduml
